server:
  port: 1234

spring:
  application:
    name: travel-log-ms

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/travel_log_db
    username: postgres
    password: Postgresql19971207.

  liquibase:
    enabled: true
#    default-schema: public
#    url: jdbc:postgresql://localhost:5432/travel_log_db
#    user: postgres
#    password: Postgresql19971207.
    change-log: db/changelog/db.changelog-master.yaml